### ISSUE TITLE
SyntaxError: invalid hexadecimal literal

### ISSUE THREAD

**Issue by rbrown256** [marnix/synology-decrypt#36]
Hi

I seem to get the following error when running on Ubuntu

```
# python3 -m syndecrypt -h                                                                                                                                                         [11:33]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/synology-decrypt/syndecrypt/__main__.py", line 25, in <module>
    import syndecrypt.files as files
  File "/opt/synology-decrypt/syndecrypt/files.py", line 6, in <module>
    import syndecrypt.core as core
  File "/opt/synology-decrypt/syndecrypt/core.py", line 4, in <module>
    from Cryptodome.Cipher import AES
  File "/home/XXXXXXXXX/.local/share/virtualenvs/synology-decrypt-PJ9kO-mR/lib/python3.10/site-packages/Cryptodome/Cipher/__init__.py", line 7, in <module>
    from Cryptodome.Cipher._mode_ctr import _create_ctr_cipher
  File "/home/XXXXXXXXX/.local/share/virtualenvs/synology-decrypt-PJ9kO-mR/lib/python3.10/site-packages/Cryptodome/Cipher/_mode_ctr.py", line 35, in <module>
    from Cryptodome.Util.number import long_to_bytes
  File "/home/XXXXXXXXX/.local/share/virtualenvs/synology-decrypt-PJ9kO-mR/lib/python3.10/site-packages/Cryptodome/Util/number.py", line 387
    s = pack('>I', n & 0xffffffffL) + s
```

A also tried the solution [here](https://www.reddit.com/r/youtubedl/comments/w7lb8x/youtubedlp_and_youtubedl_gives_me_weird_python/)

> Uninstall - pip3 uninstall pycryptodome
> Update - pip3 install -U pycryptodome
> Install cryptodomex - pip3 install pycryptodomex

Any advice?

**Comment by bensgith** [comment]
I'm having the same issue here...

**Comment by rbrown256** [comment]
@bensgith I used https://github.com/anojht/synology-cloud-sync-decrypt-tool in the end instead
